### ISSUE TITLE
Getting name 'no_TNP' is not defined error when running the macro

### ISSUE THREAD

**Issue by mik13ST** [Freedman-CB1/TopoX10#2]
I installed this macro by saving the FCMacro file into %appdata%/FreeCad/Macro folder and it is detected by FreeCAD. But when I run it, I get this:
```
16:29:50  Traceback (most recent call last):
  File "C:/Users/mik/AppData/Roaming/FreeCAD/Macro/TopoX10.FCMacro", line 17, in <module>
    __icon__ = no_TNP.svg
<class 'NameError'>: name 'no_TNP' is not defined
```

I tried also saving the two PNG and SVG to the same folder, but that didn't help.

My directory looks like this:
![image](https://user-images.githubusercontent.com/19293769/176205932-a6152554-ed4e-49c8-a6f0-88164ddb7c07.png)

How should I install this Macro correctly? Why not add it to https://github.com/FreeCAD/FreeCAD-macros so it's available in the Addon Manager?

**Comment by Freedman-CB1** [comment]
I'm really not supporting this very much and X10 is old. The latest is here on the forum: TopoXD8.https://forum.freecadweb.org/viewtopic.php?f=8&t=66186#p586781It works well with simple models but can't handle stuff like piping because the macro needs sketches to work. This was built mostly to see what it could and could not do. I can't use the addon-manager because of use restrictions so I don't do much with add-ons.Thanks, I think I will remove this from Git.


-------- Original Message --------
Subject: [Freedman-CB1/TopoX10] Getting name 'no_TNP' is not defined
error when running the macro (Issue #2)
From: mik13ST ***@***.***>
Date: Tue, June 28, 2022 7:35 am
To: Freedman-CB1/TopoX10 ***@***.***>
Cc: Subscribed ***@***.***>

 I installed this macro by saving the FCMacro file into %appdata%/FreeCad/Macro folder and it is detected by FreeCAD. But when I run it, I get this: 16:29:50  Traceback (most recent call last):
  File "C:/Users/mik/AppData/Roaming/FreeCAD/Macro/TopoX10.FCMacro", line 17, in <module>
    __icon__ = no_TNP.svg
<class 'NameError'>: name 'no_TNP' is not defined
 I tried also saving the two PNG and SVG to the same folder, but that didn't help. My directory looks like this:  How should I install this Macro correctly? Why not add it to https://github.com/FreeCAD/FreeCAD-macros so it's available in the Addon Manager? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
